### ISSUE TITLE
Research Blog Platforms (Ghost or Gatsby)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-blog#1]
**Description**
Research to see if Gatsby has equivalent SEO to Ghost.

**Tasks**
- [x] Research to see if Gatsby has equivalent SEO to Ghost.
- [x] Define Blog stack.

**Comment by faddat** [comment]
# Ghost
+ Easy Setup
+ Nice UI/UX for editing
+ Well-known SEO practices

# Gatsby
+ Generates from Markdown
+ "Serverless" -- generates static assets for us to deploy
+ Helmet for SEO
- No UI/UX for editing

----

Bottom line:  We should commit our blogs in markdown to our "blog" repository and deploy them on Ghost or Gatsby.  For now, I'm going to work on getting ghost up at https://blog.universe.engineering with Caddy as the https provider.

**Comment by guylepage3** [comment]
Hey @faddat can you provide references for your findings please? Thank you sir.

**Comment by guylepage3** [comment]
The following is research comparing Ghost to Gatsby for use as our open source blog platform.

**Some key requirements for Universe Blog**
- Beneficial to have CMS for easy deployment by teammates who do not code.
- Must have strong SEO either out of the box or with plugin but must be open and free.
- Easy deployment.

## Ghost
https://ghost.org/

- Has [CMS (Content Management) built in](https://ghost.org/features/), allowing anyone to write and publish blog posts with little to no HTML experience.
- [Open Source](https://ghost.org/features/).
- [Strong SEO](https://ghost.org/features/) - Proper SEO built in directly, with semantic markup, permalinks, XML sitemaps, canonical tags and automatic meta data with manual overrides.
- [Fully customizable UI](https://ghost.org/features/).
- [Familiar tooling. ie. Node, Express, Ember, Handlebars, etc](https://ghost.org/features/).
- [Easy to deploy to GCP](https://cloud.google.com/community/tutorials/ghost-on-app-engine-part-1-deploying).
- [Vibrant community of over 10,000 Ghost users](https://ghost.org/features/).
- Strong [documentation](https://ghost.org/docs/) and [tutorials](https://ghost.org/tutorials/).

## Gatsby
https://www.gatsbyjs.org/

- Generates from Markdown (@faddat can you provide evidence of this?)
- Offers SEO through [Helmet SEO](https://www.gatsbyjs.org/docs/add-seo-component/).
- "Serverless" -- generates static assets for us to deploy (@faddat can you provide evidence of this?)
- Strong ecosystem as Gatsby is being used for more than blogging.
- Strong [documentation](https://www.gatsbyjs.org/docs/).
- No CMS.

**Comment by guylepage3** [comment]
Hey @faddat I've done a deeper dive into Ghost vs. Gatsby. 

I have not come to a conclusion on which is best to use as of yet. I feel we should spin up an instance of each of the two since they are both quite easy to setup and get going. From there we can decide which will work for us.

**Comment by guylepage3** [comment]
Hey @faddat @modkaffes I've done a deeper dive into Ghost vs. Gatsby.

I have not come to a conclusion on which is best to use as of yet. I feel we should spin up an instance of each of the two since they are both quite easy to setup and get going. From there we can decide which will work for us.

Thoughts?

**Comment by faddat** [comment]
Regarding static assets, here's a shot from the gatsby site showing this:

<img width="590" alt="Screen Shot 2019-09-05 at 4 22 23 PM" src="https://user-images.githubusercontent.com/7142025/64377886-74821800-cff9-11e9-98ce-0492ba2588c2.png">

So, for example, we could have Markdown on Github, make it all pretty with Gatsby, and then host that on GitHub pages and have an automated flow for that.  

Or, we could do the same and self-host the content with Caddy.

**Comment by guylepage3** [comment]
NICE! I really like this @faddat. 😄

**Comment by faddat** [comment]
We've decided to go with gatsby :).  

@modkaffes can you help us get rolling and let me know if we need a server for it?

**Comment by guylepage3** [comment]
@modkaffes @faddat and I made the decision to go with Gatsby. Either you or I can set this up. Let me know your timing sir. Thank you.

**Comment by modkaffes** [comment]
I can bootstrap it tonight inside this repo. OK?

**Comment by guylepage3** [comment]
That would be awesome @modkaffes 😄 Thank you sir.

**Comment by guylepage3** [comment]
Please note @modkaffes, the blog is not at all a priority at the moment. Please do not spent a second on this at this time. Thank you.
